/*
    Boost Software License - Version 1.0 - August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/

#ifndef CTRGL_H
#error Please do not include this file directly. Use <gl.h> instead.
#endif

enum GLbooleanValue
{
    GL_FALSE =                  0,
    GL_TRUE =                   1,
};

enum GLblendMode
{
    GL_FUNC_ADD =               0,
    GL_FUNC_SUBTRACT =          1,
    GL_FUNC_REVERSE_SUBTRACT =  2,
    GL_MIN =                    3,
    GL_MAX =                    4,
};

enum GLblendFactor
{
    GL_ZERO =                       0,
    GL_ONE =                        1,
    GL_SRC_COLOR =                  2,
    GL_ONE_MINUS_SRC_COLOR =        3,
    GL_DST_COLOR =                  4,
    GL_ONE_MINUS_DST_COLOR =        5,
    GL_SRC_ALPHA =                  6,
    GL_ONE_MINUS_SRC_ALPHA =        7,
    GL_DST_ALPHA =                  8,
    GL_ONE_MINUS_DST_ALPHA =        9,
    GL_CONSTANT_COLOR =             10,
    GL_ONE_MINUS_CONSTANT_COLOR =   11,
    GL_CONSTANT_ALPHA =             12,
    GL_ONE_MINUS_CONSTANT_ALPHA =   13,
    GL_SRC_ALPHA_SATURATE =         14,
};

enum GLbufferAccess
{
    GL_READ_ONLY,
    GL_WRITE_ONLY,
    GL_READ_WRITE,
};

/* lol we completely disregard all of these anyway */
enum GLbufferMapBits
{
    GL_MAP_READ_BIT =               1,
    GL_MAP_WRITE_BIT =              2,
    GL_MAP_INVALIDATE_RANGE_BIT =   4,
    GL_MAP_INVALIDATE_BUFFER_BIT =  8,
    GL_MAP_UNSYNCHRONIZED_BIT =     16,
};

enum GLbufferTarget
{
    GL_ARRAY_BUFFER
};

enum GLbufferUsage
{
    GL_STREAM_DRAW,
    GL_STREAM_READ,
    GL_STREAM_COPY,
    GL_STATIC_DRAW,
    GL_STATIC_READ,
    GL_STATIC_COPY,
    GL_DYNAMIC_DRAW,
    GL_DYNAMIC_READ,
    GL_DYNAMIC_COPY,
};

enum GLcaps
{
    /* flags */
    GL_CULL_FACE =      0x0001,
    GL_STENCIL_TEST =   0x0002,
    GL_BLEND =          0x0004,
    GL_ALPHA_TEST =     0x0008,
    GL_DEPTH_TEST =     0x0010,

    /* non-flags */
    GL_TEXTURE_2D =     0x8000,

    /* internal, do NOT use in any API calls */
    GL_SHADER_PROGRAM_CTR = 0x00010000,
    GL_TEXTURING_CTR =      0x00020000,
    GL_VERTEX_ARRAYS_CTR =  0x00040000,
    GL_MATRICES_CTR =       0x00080000,
};

enum GLcombineFunc
{
    GL_REPLACE =        0x00,
    GL_MODULATE =       0x01,
    GL_ADD =            0x02,
    GL_ADD_SIGNED =     0x03,
    GL_INTERPOLATE =    0x04,
    GL_SUBTRACT =       0x05,
    GL_DOT3_RGB =       0x06,
};

enum GLcullFaceMode
{
    GL_FRONT =      0,
    GL_BACK =       1,
    /*GL_FRONT_AND_BACK -- not supported by POS PICA?*/
};

enum GLfrontFaceMode
{
    GL_CW =         0,
    GL_CCW =        1,
};

enum GLmatrixMode
{
    GL_PROJECTION = 0,
    GL_MODELVIEW = 1,
};

enum GLprimitiveMode {
    GL_TRIANGLES =      0x0000,
    GL_TRIANGLE_STRIP = 0x0100,
    GL_TRIANGLE_FAN =   0x0200,
};

enum GLstencilOp
{
    GL_KEEP =       0,
    GL_AND_NOT =    1,
    GL_XOR =        5,
};

enum GLtestFunc
{
    GL_NEVER =      0,
    GL_ALWAYS =     1,
    GL_EQUAL =      2,
    GL_NOTEQUAL =   3,
    GL_LESS =       4,
    GL_LEQUAL =     5,
    GL_GREATER =    6,
    GL_GEQUAL =     7,
};

enum GLtevSrc
{
    GL_PRIMARY_COLOR =  0x00,
    GL_TEXTURE0 =       0x03,
    GL_TEXTURE1 =       0x04,
    GL_TEXTURE2 =       0x05,
    GL_TEXTURE3 =       0x06,
    GL_CONSTANT =       0x0E,
    GL_PREVIOUS =       0x0F,
};

enum GLtexEnvPname
{
    GL_TEXTURE_ENV_COLOR
};

enum GLtexEnvTarget
{
    GL_TEXTURE_ENV
};

enum GLtextureInternalFormat
{
    GL_BLOCK_RGBA8_CTR =    0,
};

enum GLtextureFormat
{
    GL_BLOCK_RGBA_CTR =     0,
};

enum GLtype
{
    GL_BYTE =           0,
    GL_UNSIGNED_BYTE =  1,
    GL_SHORT =          2,
    GL_FLOAT =          3,
};

/* CTR extensions */

typedef enum
{
    GL_MEMORY_STATIC_CTR,
    GL_MEMORY_COPY_CTR,
    GL_MEMORY_TRANSFER_CTR,
}
GLmemoryTransferModeCTR;
